name: step02_condition
on: workflow_dispatch
jobs:
  build:
    if: github.repository == '깃허브id/github-action-test'
    runs-on: ubuntu-latest
    steps:
    - name: Print Result
      run: |
        echo "Run Build on 202011988/github-action-test"
