name: step01_basic
on: workflow_dispatch
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Project
      run: |
        echo "Build Project"
  deploy:
    needs: build #build 수행 이후 deploy 수행
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Project
      run: |
        echo "Deploy Project"
